version: '3.4'

services:
  sqldata:
    image: mcr.microsoft.com/mssql/server
    container_name: sql1
    hostname: sql1
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 1433:1433

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

  company-course-api:
    container_name: company-course-api
    build:
      context: .
      dockerfile: Company.Course/Company.Course.Api/Dockerfile
    depends_on:
      - sqldata
      - rabbitmq

  company-department-api:
    container_name: company-department-api
    build:
      context: .
      dockerfile: Company.Department/Company.Department.Api/Dockerfile
    depends_on:
      - sqldata
      - rabbitmq

  company-employee-api:
    container_name: company-employee-api
    build:
      context: .
      dockerfile: Company.Employee/Company.Employee.Api/Dockerfile
    depends_on:
      - sqldata
      - rabbitmq

  company-notification-api:
    container_name: company-notification-api
    build:
      context: .
      dockerfile: Company.Notification/Company.Notification.Api/Dockerfile
    depends_on:
      - sqldata
      - rabbitmq

  microservices-catalogue:
    container_name: microservices-catalogue
    build:
      context: .
      dockerfile: Microservices.Catalogue/Dockerfile
    depends_on:
      - company-course-api
      - company-department-api
      - company-employee-api
      - company-notification-api
    ports:
      - 3100:3000