apiVersion : apps/v1
kind: Deployment
metadata:
  name: company-course
spec:
  replicas: 2
  selector:
    matchLabels:
      app: company-course
  template:
    metadata:
      labels:
        app: main_pod_company_course
    spec:
      containers:
        - name: company-course
          image: devcontainerregistryre02.azurecr.io/company-course
          ports:
          - containerPort: 80
          - containerPort: 433
