apiVersion : apps/v1
kind: Deployment
metadata:
  name: company-employee-deployment
  labels:
    app: main_deployment_company_employee
spec:
  replicas: 2
  selector:
    matchLabels:
      app: main_deployment_company_employee
  template:
    metadata:
      labels:
        app: main_deployment_company_employee
    spec:
      containers:
        - name: company-employee
          image: devcontainerregistryre02.azurecr.io/company-employee
          ports:
          - containerPort: 80
          - containerPort: 433                                                             
