apiVersion: v1
kind: Service
metadata:
    name: "devkubernetesre01-ca2c"
    labels:
        app: "devkubernetesre01-ca2c"
spec:
    type: LoadBalancer
    ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
    selector:
        app: "devkubernetesre01-ca2c"