apiVersion: v1
kind: Pod
metadata:
  name: company-course
  labels:
    app: company-course  
spec:
  containers:
  - name: company-course
    image: devcontainerregistryre02.azurecr.io/company-course
    ports:
    - containerPort: 80
    - containerPort: 433
