name: CI
on: [push, pull_request]

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@master

        - name: 'Login via Azure CLI'
          uses: Azure/docker-login@v1
          with:
              login-server: devcontainerregistryre02.azurecr.io
              username: ${{ SECRETS.REGISTRY_USERNAME }}
              password: ${{ SECRETS.REGISTRY_PASSWORD }}

        - run: |
            docker build . -t devcontainerregistryre02.azurecr.io/monorepo-microservices-demo:${{ github.sha }}
            docker push devcontainerregistryre02.azurecr.io/monorepo-microservices-demo:${{ github.sha }}

        - name: 'Azure Login'
          uses: azure/login@v1
          with:
            creds: ${{ SECRETS.AZURE_CREDENTIALS }}

        - name: 'Deploy to Azure Container Instances'
          uses: azure/aci-deploy@v1
          with:
            resource-group: dev-container-registry-re02
            name: monorepo-microservices-demo
            image: devcontainerregistryre02.azurecr.io/monorepo-microservices-demo:${{ github.sha }}
            ports: 80 8080
            dns-name-label: monorepo-microservices-demo
            registry-login-server: devcontainerregistryre02.azurecr.io
            registry-username: ${{ SECRETS.REGISTRY_USERNAME }}
            registry-password: ${{ SECRETS.REGISTRY_PASSWORD }}
            location: canadacentral