name: Build Microservices and Catalogue

on:
  workflow_dispatch:
  
jobs:
  build_microservice_courses:
    runs-on: ubuntu-latest
    defaults:
          run:
            working-directory: ./Company.Course
            
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
  build_microservice_departments:
    runs-on: ubuntu-latest
    defaults:
          run:
            working-directory: ./Company.Department
            
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal      
      
  build_microservice_employees:
    runs-on: ubuntu-latest
    defaults:
          run:
            working-directory: ./Company.Employee
            
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal      

  build_microservice_notification:
    runs-on: ubuntu-latest
    defaults:
          run:
            working-directory: ./Company.Notification
            
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal 
      
  build_catalogue_react:
    runs-on: ubuntu-latest
    needs: [build_microservice_courses, build_microservice_departments, build_microservice_employees, build_microservice_notification]
    defaults:
          run:
            working-directory: ./Microservices.Catalogue
            
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: "npm"

      - name: npm install and build
        run: |
          npm install
          npm run build --if-present       
        env:
          CI: false      
