name: Build Microservices and Catalogue

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME_1: dev-aspnet-company-course-re01
  AZURE_WEBAPP_NAME_2: dev-aspnet-company-department-re01
  AZURE_WEBAPP_NAME_3: dev-aspnet-company-employee-re01
  AZURE_WEBAPP_NAME_4: dev-aspnet-company-notification-re01
  AZURE_WEBAPP_NAME_5: dev-aspnet-microservices-catalogue-re01
  AZURE_WEBAPP_PACKAGE_PATH: "."
  NODE_VERSION: "14.x"

jobs:
  build_microservice_courses:
    runs-on: ubuntu-latest
    defaults:
          run:
            working-directory: ./Company.Course
            
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
  build_microservice_departments:
    runs-on: ubuntu-latest
    defaults:
          run:
            working-directory: ./Company.Department
            
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal      
      
  build_microservice_employees:
    runs-on: ubuntu-latest
    defaults:
          run:
            working-directory: ./Company.Employee
            
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal      

  build_microservice_notification:
    runs-on: ubuntu-latest
    defaults:
          run:
            working-directory: ./Company.Notification
            
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal 
      
  build_catalogue_react:
    runs-on: ubuntu-latest
    needs: [build_microservice_courses, build_microservice_departments, build_microservice_employees, build_microservice_notification]
    defaults:
          run:
            working-directory: ./Microservices.Catalogue
            
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - name: npm install and build
        run: |
          npm install
          npm run build --if-present       
        env:
          CI: false

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app-1
          path: ./Microservices.Catalogue/build          
  
  update_packages_version:
    runs-on: ubuntu-latest
    needs: [build_catalogue_react]

    steps:
      - uses: actions/checkout@v2
      - name: Bot Configuration
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Standard Version 
        run: |
          npx standard-version
          git push --follow-tags origin HEAD:main 

  deploy_microservices_catalogue:
    runs-on: ubuntu-latest
    needs: [build_catalogue_react, update_packages_version]

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app-1

      - name: "Deploy to dev-aspnet-microservices-catalogue-re01"
        id: deploy-to-webapp-5
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME_5 }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_MICROSERVICES_CATALOGUE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}          
