name: Azure Push Images to Registry

on:
  workflow_dispatch:

jobs:
    build_and_push_to_registry:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout GitHub Action
          uses: actions/checkout@v2

        - name: Login via Azure CLI
          uses: Azure/docker-login@v1
          with:
              login-server: devcontainerregistryre02.azurecr.io
              username: ${{ SECRETS.REGISTRY_USERNAME }}
              password: ${{ SECRETS.REGISTRY_PASSWORD }}

        - name: Push Company.Course to Registry
          run: |
            docker build -f ./Company.Course/Company.Course.Api/Dockerfile -t devcontainerregistryre02.azurecr.io/company-course:ci-1.0.1 .
            docker push devcontainerregistryre02.azurecr.io/company-course:ci-1.0.1
            
        - name: Push Company.Department to Registry
          run: |
            docker build -f ./Company.Department/Company.Department.Api/Dockerfile -t devcontainerregistryre02.azurecr.io/company-department:ci-1.0.1 .
            docker push devcontainerregistryre02.azurecr.io/company-department:ci-1.0.1
            
        - name: Push Company.Employee to Registry
          run: |
            docker build -f ./Company.Employee/Company.Employee.Api/Dockerfile -t devcontainerregistryre02.azurecr.io/company-employee:ci-1.0.1 .
            docker push devcontainerregistryre02.azurecr.io/company-employee:ci-1.0.1

        - name: Push Company.Notification to Registry
          run: |
            docker build -f ./Company.Notification/Company.Notification.Api/Dockerfile -t devcontainerregistryre02.azurecr.io/company-notification:ci-1.0.1 .
            docker push devcontainerregistryre02.azurecr.io/company-notification:ci-1.0.1

        - name: Push Microservices.Catalogue to Registry
          run: |
            docker build -f ./Microservices.Catalogue/Dockerfile -t devcontainerregistryre02.azurecr.io/microservices-catalogue:ci-1.0.1 .
            docker push devcontainerregistryre02.azurecr.io/microservices-catalogue:ci-1.0.1            
